/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pa_pbo;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Random;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class BuatAkta extends javax.swing.JFrame {
    
    
    DBCon con;
    
    /**
     * Creates new form BuatAkta
     */
    public BuatAkta() {
        initComponents();
        this.con = new DBCon();
    }
    
    private static String generateRandomNIK() {
        Random random = new Random();
        int randomNik = 100000000 + random.nextInt(900000000); // NIK 9 digit acak
        return String.valueOf(randomNik);
    }
    
    private String getCurrentDate() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date today = new Date();
        return dateFormat.format(today);
    }
    
    private static String generateRandomID() {
        Random random = new Random();
        int randomNik = 100 + random.nextInt(900); // ID 3 digit acak
        return String.valueOf(randomNik);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jenistxt = new javax.swing.JTextField();
        tanggaltxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        anaktxt = new javax.swing.JTextField();
        kirimbtn = new javax.swing.JButton();
        namatxt = new javax.swing.JTextField();
        kembalibtn = new javax.swing.JButton();
        tempattxt = new javax.swing.JTextField();
        jlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Tanggal Lahir (YYYY-MM-DD):");

        jLabel4.setText("Tempat Lahir:");

        jLabel5.setText("Jenis Kelamin:");

        tanggaltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggaltxtActionPerformed(evt);
            }
        });

        jLabel1.setText("Anak Ke:");

        anaktxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anaktxtActionPerformed(evt);
            }
        });

        kirimbtn.setText("Kirim");
        kirimbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kirimbtnActionPerformed(evt);
            }
        });

        namatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namatxtActionPerformed(evt);
            }
        });

        kembalibtn.setText("Kembali");
        kembalibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalibtnActionPerformed(evt);
            }
        });

        jlabel.setText("Nama:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1))
                                .addGap(87, 87, 87))
                            .addComponent(jLabel3)
                            .addComponent(jlabel)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jenistxt, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                                .addComponent(anaktxt))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tanggaltxt)
                                .addComponent(namatxt, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                                .addComponent(tempattxt, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(kembalibtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                        .addComponent(kirimbtn)))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel)
                    .addComponent(namatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tanggaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tempattxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jenistxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(anaktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kirimbtn)
                    .addComponent(kembalibtn))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tanggaltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggaltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggaltxtActionPerformed

    private void anaktxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anaktxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anaktxtActionPerformed

    private void kirimbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kirimbtnActionPerformed

        String id = generateRandomID();
        String date = getCurrentDate();
        String kategori = "Akta";
        String status = "Belum Disetujui";
        
        String nik = generateRandomNIK();
        String nama = namatxt.getText();
        String tanggal = tanggaltxt.getText();
        String tempat = tempattxt.getText();
        String jenis = jenistxt.getText();
        String anak = anaktxt.getText();
        
        try (Connection conn = con.create_connection();  
                PreparedStatement ps =  conn.prepareStatement("INSERT INTO surat (nik, nama, tanggal_lahir, tempat_lahir, jenis_kelamin) VALUES (?, ?, ?, ?, ?)");
                PreparedStatement stm = conn.prepareStatement("INSERT INTO akte_kelahiran (nik, anakke) VALUES (?, ?)");
                PreparedStatement stmn = conn.prepareStatement("INSERT INTO laporan_surat (id, tanggal, status, kategori) VALUES (?, ?, ?, ?)")
                
            )
        {
            ps.setString(1, nik);
            ps.setString(2, nama);
            ps.setString(3, tanggal);
            ps.setString(4, tempat);
            ps.setString(5, jenis);
            
            stm.setString(1, nik);
            stm.setString(2, anak);
            
            stmn.setString(1, id);
            stmn.setString(2, date);
            stmn.setString(3, status);
            stmn.setString(4, kategori);
            
            ps.executeUpdate();
            stm.executeUpdate();
            stmn.executeUpdate();
            
            System.out.println("Register Berhasil");
            
            JOptionPane.showMessageDialog(null, "Akta Berhasil Dibuat, Mohon Menunggu Verifikasi", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
            MenuUser menuUser = new MenuUser();
            menuUser.setVisible(true);
            this.dispose();
            
 
        } catch (SQLException ex) {
            System.out.println(ex);    
        }
    }//GEN-LAST:event_kirimbtnActionPerformed

    private void namatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namatxtActionPerformed

    private void kembalibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalibtnActionPerformed
        BuatSurat buatSurat = new BuatSurat();
        buatSurat.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kembalibtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuatAkta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuatAkta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuatAkta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuatAkta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuatAkta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anaktxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jenistxt;
    private javax.swing.JLabel jlabel;
    private javax.swing.JButton kembalibtn;
    private javax.swing.JButton kirimbtn;
    private javax.swing.JTextField namatxt;
    private javax.swing.JTextField tanggaltxt;
    private javax.swing.JTextField tempattxt;
    // End of variables declaration//GEN-END:variables
}
